# Generated by Django 4.2.3 on 2023-07-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='city',
            field=models.TextField(default=''),
        ),
    ]
